

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y wget
        go mod tidy
        go mod download

    - name: Install nfpm
      run: |
        go install github.com/goreleaser/nfpm@latest
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

    - name: Build multi-platform binaries
      run: ./scripts/build-multiplatform.sh test

    - name: Build packages
      run: ./scripts/build-packages.sh test

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Check out code
      uses: actions/checkout@v3

    - name: Run tests
      run: |
        echo "Running tests..."
        # Add test commands here when tests are available

