

name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-26.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: 'go.mod'

    - name: Verify modules
      run: |
        go mod verify

    - name: Run static analysis
      run: |
        go vet ./...

    - name: Run tests
      run: |
        go test -race ./...

